[versions]
accompanistPermissions = "0.37.3"
androidGradlePlugin = "8.13.1"
compose = "1.9.3"
coreSplashscreen = "1.0.1"
kotlin = "2.2.0"
kotlinxSerializationJson = "1.9.0"
hiltAndroid = "2.57.2"
hiltAndroidx = "1.3.0"
navigation = "2.9.5"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
compose-ui-android = { module = "androidx.compose.ui:ui-android", version.ref = "compose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-androidx-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltAndroidx" }
hilt-androidx-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltAndroidx" }
navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin" }
